<?php require 'templates/header.phtml'; ?>

<div>
    <h1>Editar Categoría</h1>
    <form method="POST" action="update_categoria">
        <input type="hidden" name="id" value="<?php echo $categoria->ID_categoria; ?>">
        
        <label>Temporada:</label>
        <input type="text" name="temporada" value="<?php echo $categoria->temporada; ?>" required>
        
        <label>Empresa:</label>
        <input type="text" name="empresa" value="<?php echo $categoria->empresa; ?>" required>
        
        <label>Comodidad:</label>
        <input type="text" name="comodidad" value="<?php echo $categoria->comodidad; ?>" required>

        <button type="submit">Actualizar</button>
    </form>
</div>

<?php require 'templates/footer.phtml'; ?>