<?php require './templates/header.phtml'; ?>

<div class="card">
    <h2>Detalles de la Categoría y los Viajes Relacionados</h2>

    <div class="card">
        <!-- Mostrar detalles de la categoría -->
        <h3>Detalles de la Categoría</h3>
        <ul>
            <li><strong>Temporada:</strong> <?= $categoria->temporada ?></li>
            <li><strong>Empresa:</strong> <?= $categoria->empresa ?></li>
            <li><strong>Comodidad:</strong> <?= $categoria->comodidad ?></li>
        </ul>
        
        <!-- Mostrar los viajes relacionados con esta categoría -->
        <h3>Viajes Relacionados</h3>
        <?php if (empty($viaje)): ?>
            <p>No hay viajes disponibles para esta categoría.</p>
        <?php else: ?>
            <ul>
                <?php foreach ($viaje as $viajes): ?>
                    <li>
                        <strong>Fecha de salida:</strong> <?= $viajes->Fecha ?><br>
                        <strong>Hora de salida:</strong> <?= $viajes->Hora ?><br>
                        <strong>Origen:</strong> <?= $viajes->Origen ?><br>
                        <strong>Destino:</strong> <?= $viajes->Destino ?>
                    </li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
    </div>
</div>

<?php require './templates/footer.phtml'; ?>