<?php require_once './templates/header.phtml'; ?>

<div>
    <h1>Listado de Categoria</h1>
    <table>
        <thead>
            <tr>
                <th>Temporda</th>
                <th>Empresa</th>
                <th>Comodidad</th>     
           </tr>
        </thead>
        <tbody>
        <?php foreach ($categoria as $categorias): ?> 
    <tr>
        <td><?php echo $categorias->temporada; ?></td> <!-- Acceder correctamente a las propiedades del objeto -->
        <td><?php echo $categorias->empresa; ?></td>
        <td><?php echo $categorias->comodidad; ?></td>
        <td>
            <a href="editarCategoria/<?php echo $categorias->id; ?>">Editar Categoria</a>
            <a href="eliminarCategoria/<?php echo $categorias->id; ?>">Eliminar</a>
        </td>
        <td>
            <a href="<?= BASE_URL ?>verMasViajes/<?= $categorias->id ?>">Ver Más</a>
        </td>
    </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>


<?php require_once './templates/footer.phtml'; ?>