<?php require_once './templates/header.phtml'; ?>

<div>
    <h1>Listado de Categoria</h1>
    <table>
        <thead>
            <tr>
                <th>Temporada</th>
                <th>Empresa</th>
                <th>Comodidad</th>   
                <th>Acciones</th>  
           </tr>
        </thead>
        <tbody>
        <?php foreach ($categorias as $categoria): ?> 
    <tr>
        <td><?php echo $categoria->temporada; ?></td> <!-- Acceder correctamente a las propiedades del objeto -->
        <td><?php echo $categoria->empresa; ?></td>
        <td><?php echo $categoria->comodidad; ?></td>
        <td>
            <a href="mostrarFormEditCategoria/<?php echo $categoria->id; ?>">Editar Categoria</a>
            <a href="eliminarCategoria/<?php echo $categoria->id; ?>">Eliminar</a>
            <a href="<?= BASE_URL ?>verMasCategoria/<?= $categoria->id ?>">Ver Más</a>
        </td>
    </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>


<?php require_once './templates/footer.phtml'; ?>