<?php require './templates/header.phtml'; ?>

<div>
    <h2 class="display-6 text-center mb-4">Detalles de la Categoria</h2>
    
    <div>
        <div>
            <ul class="list-group list-group-flush">
                <li><strong>Temporada:</strong> <?= $categoria->temporada ?></li>
                <li><strong>Empresa:</strong> <?= $categoria->empresa ?></li>
                <li><strong>Comodidad:</strong> <?= $categoria->comodidad ?></li>   
             </ul>
        </div>
    </div>

    <h2 class="display-6 text-center mb-4">Editar Categorias</h2>
    
    <div >
        <div >
            <form action="<?= BASE_URL ?>editarCategoria/<?= $ID_categoria ?>" method="POST" novalidate>
                <div>
                    <label for="temporada">Temporada</label>
                    <input type="text" id="temporada" name="temporada" value="<?= $categoria->temporada ?>" required>
                </div>

                <div>
                    <label for="empresa">Empresa</label>
                    <input type="text" id="empresa" name="empresa" value="<?= $categoria->empresa ?>" required>
                </div>

                <div>
                    <label for="comodidad">Comodidad</label>
                    <input type="text" id="comodidad" name="comodidad" value="<?= $categoria->comodidad ?>" required>
                </div>


                <div>
                    <button type="submit">Actualizar Categorias</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require './templates/footer.phtml'; ?>