<?php require 'templates/header.phtml'; ?>

<div>
    <h2 class="display-6 text-center mb-4">Detalles de la Categoria</h2>
    
    <div>
        <div>
            <ul class="list-group list-group-flush">
                <li><strong>Temporada:</strong> <?= $categoria->temporada ?></li>
                <li><strong>Empresa:</strong> <?= $persona->empresa ?></li>
                <li><strong>Comodidad:</strong> <?= $persona->comodidad ?></li>   
             </ul>
        </div>
    </div>

    <h2 class="display-6 text-center mb-4">Editar Categorias</h2>
    
    <div >
        <div >
            <form action="<?= BASE_URL ?>editarCategoria/<?= $ID_categoria ?>" method="POST" novalidate>
                <div>
                    <label for="temporadaa">Temporada</label>
                    <input type="text" id="temporadaa" name="temporada" value="<?= $categoria->temporada ?>" required>
                    <div>Por favor, ingresa una temporada válido.</div>
                </div>

                <div>
                    <label for="empresaa">Empresa</label>
                    <input type="text" id="empresaa" name="empresa" value="<?= $categoria->empresa ?>" required>
                    <div class="invalid-feedback">Por favor, ingresa una empresa válido.</div>
                </div>

                <div>
                    <label for="comodidadd">Comodidad</label>
                    <input type="number" class="form-control" id="validationCustom03" name="dni" value="<?= $persona->dni ?>" required>
                    <div class="invalid-feedback">Por favor, ingresa un DNI válido.</div>
                </div>


                <div>
                    <buttontype="submit">Actualizar Categorias</button>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml'; ?>