<?php require 'templates/header.phtml'; ?>

<div >
    <h2>Detalles del Viaje</h2>

    <div>
        <div>
            <ul>
                <li><strong>Destino de Inicio:</strong> <?= $viaje->Destino ?></li>
                <li><strong>Destino de Llegada:</strong> <?= $viaje->Origen ?></li>
                <li><strong>Fecha de Salida:</strong> <?= $viaje->Fecha?></li>
                <li><strong>Precio:</strong> $<?= $viaje->Hora ?></li>


            </ul>
        </div>
    </div>
</div>

<?php require 'templates/footer.phtml'; ?>