<?php require 'templates/header.phtml'; ?>

<div class="container mt-5">
    <h2 class="display-6 text-center mb-4">Detalles del Viaje</h2>

    <div class="card">
        <div>
            <ul>
                <li><strong>Fecha de salida:</strong> <?= $viaje->Fecha ?></li>
                <li><strong>Hora de salida:</strong> <?= $viaje->Hora ?></li>
                <li><strong>Origen:</strong> <?= $viaje->Origen ?></li>
                <li><strong>Destino:</strong> <?= $viaje->Destino ?></li>
                <li><strong>Temporada</strong><?=$categoria-> temporada?></li>
            </ul>
        </div>
    </div>
</div>

<div>
    <h1>Editar Viaje</h1>
    <form method="POST" action="<?= BASE_URL ?>update/<?= $id ?>">
        <input type="hidden" name="id" value="<?php echo $viaje->ID_viaje; ?>">
        <div>
        <label for="fecha">Fecha de Viaje</label>
            <input type="date" id="fecha" name="Fecha" required>
        </div>
        <div class="col1">
            <label for="hora">Horario</label>
            <input type="number" id="hora" name="Hora" required>
        </div>
        <div class="col1">
            <label for="origen">Origen</label>
            <input type="text" id="origen" name="Origen" required>
        </div>
        <div class="col1">
            <label for="destino">Destino</label>
            <input type="text" id="destino" name="Destino" required>
        </div>

         <!-- Campo para editar la Categoría -->
         <label for="id_categoria">Temporada:</label>
            <select name="id_categoria" required>
                <?php foreach ($categoria as $categorias): ?>
                    <option value="<?= $categorias->id ?>" <?= ($viaje->id == $categorias->id) ? 'selected' : '' ?>>
                    <?= $categorias->temporada ?>
                </option>
                <?php endforeach; ?>
            </select>
        </div> 

        <button type="submit">Actualizar</button>
    </form>
</div>

<?php require 'templates/footer.phtml'; ?>