<?php require_once './templates/header.phtml'; ?>

<div>
    <h1>Agregar Nuevo Viaje</h1>
    <form action="<?= BASE_URL ?>agregar" method="POST" novalidate>
    <div class="col1">
            <label for="fecha">Fecha de Viaje</label>
            <input type="date" id="fecha" name="Fecha" required>
        </div>
        <div class="col1">
            <label for="hora">Horario</label>
            <input type="number" id="hora" name="Hora" required>
        </div>
        <div class="col1">
            <label for="origen">Origen</label>
            <input type="text" id="origen" name="Origen" required>
        </div>
        <div class="col1">
            <label for="destino">Destino</label>
            <input type="text" id="destino" name="Destino" required>
        </div>

        <div class="col1">
      <!-- CATEGORIAS-->
      <label for="id_cateoria">Categorias:</label>
            <select name="id_categoria" required>
                <?php foreach ($categoria as $categorias): ?>
                   
                    <option value="<?= $categorias->id ?>"><?php echo $categorias->temporada?>-<?php echo $categorias->empresa?>-<?php echo $categorias->comodidad?></option>
                <?php endforeach; ?>
            </select>
        </div>  

            <button type="submit">Agregar Viaje</button>
        </div>
    </form>
</div>

<?php require_once './templates/footer.phtml'; ?>