<?php require './templates/header.phtml'; ?>
<div class="conteinerFormEditar">
<div class="listaViaje">
    <h3>Detalles del Viaje</h3>

    <div class="card">
        <div>
            <ul>
                <li><strong>Fecha de salida:</strong> <?= $viaje->Fecha ?></li>
                <li><strong>Hora de salida:</strong> <?= $viaje->Hora ?></li>
                <li><strong>Origen:</strong> <?= $viaje->Origen ?></li>
                <li><strong>Destino:</strong> <?= $viaje->Destino ?></li>
                <li><strong>Temporada:</strong><?=$categoria-> temporada?></li>
                <li><strong>Empresa:</strong><?=$categoria-> empresa?></li>
                <li><strong>Comodidad:</strong><?=$categoria-> comodidad?></li>
            </ul>
        </div>
    </div>
</div>

<div class="formEditar">
    <h3>Editar Viaje</h3>
    <form method="POST" action="<?= BASE_URL ?>update/<?= $ID_viaje ?>">
        <input type="hidden" name="id" value="<?php echo $viaje->ID_viaje; ?>">
        <div>
        <label for="fecha">Fecha de Viaje</label>
            <input type="date" id="fecha" name="Fecha" required>
        </div>
        <div class="col1">
            <label for="hora">Horario</label>
            <input type="number" id="hora" name="Hora" required>
        </div>
        <div class="col1">
            <label for="origen">Origen</label>
            <input type="text" id="origen" name="Origen" required>
        </div>
        <div class="col1">
            <label for="destino">Destino</label>
            <input type="text" id="destino" name="Destino" required>
        </div>

         <!-- Campo para editar la Categoría -->
         <label for="id_categoria">Temporada:</label>
            <select name="id_categoria" required>
                <?php foreach ($categorias as $categoria): ?>
                    <option value="<?= $categoria->id ?>"><?php echo $categoria->temporada?>-<?php echo $categoria->empresa?>-<?php echo $categoria->comodidad?></option>
                </option>
                <?php endforeach; ?>
            </select>
        <div class="col1">
            <button type="submit">Actualizar</button>
        </div>
    </form>
</div>
</div>

<?php require './templates/footer.phtml'; ?>