<?php require './templates/header.phtml'; ?>

<div class="container mt-5">
    <h2 class="display-6 text-center mb-4">Detalles del Viaje</h2>

    <div class="card">
        <div>
            <ul>
                <li><strong>Fecha de salida:</strong> <?= $viaje->Fecha ?></li>
                <li><strong>Hora de salida:</strong> <?= $viaje->Hora ?></li>
                <li><strong>Origen:</strong> <?= $viaje->Origen ?></li>
                <li><strong>Destino:</strong> <?= $viaje->Destino ?></li>
                <li><strong>Temporada:</strong><?=$categoria->temporada?></li>
                <li><strong>Empresa:</strong><?=$categoria->empresa?></li>
                <li><strong>Comodidad:</strong><?=$categoria->comodidad?></li>

            </ul>
        </div>
    </div>
</div>

<div>
    <h1>Editar Viaje</h1>
    <form method="POST" action="<?= BASE_URL ?>update/<?= $ID_viaje ?>">
        <input type="hidden" name="id" value="<?php echo $viaje->ID_viaje; ?>">

        <!-- Campo para editar el Origen -->
        <label for="Origen">Origen:</label>
        <input type="text" name="Origen" id="Origen" value="<?php echo $viaje->Origen; ?>" required>

        <!-- Campo para editar el Destino -->
        <label for="Destino">Destino:</label>
        <input type="text" name="Destino" id="Destino" value="<?php echo $viaje->Destino; ?>" required>

        <!-- Campo para editar la Fecha -->
        <label for="Fecha">Fecha:</label>
        <input type="date" name="Fecha" id="Fecha" value="<?php echo $viaje->Fecha; ?>" required>

        <!-- Campo para editar la Hora -->
        <label for="Hora">Hora:</label>
        <input type="time" name="Hora" id="Hora" value="<?php echo $viaje->Hora; ?>" required>

         <!-- Campo para editar la Categoría -->
         <label for="id_categoria">Temporada:</label>
            <select name="id_categoria" required>
                <?php foreach ($categorias as $categoria): ?>
                    <option value="<?= $categoria->id ?>"><?php echo $categoria->temporada?>-<?php echo $categoria->empresa?>-<?php echo $categoria->comodidad?></option>
                </option>
                <?php endforeach; ?>
            </select>
        </div> 
        <button type="submit">Actualizar</button>
    </form>
</div>

<?php require './templates/footer.phtml'; ?>