<?php require_once 'templates/header.phtml'; ?>

<div>
    <h1>Listado de Viajes</h1>
    <table>
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Hora</th>
                <th>Origen</th>
                <th>Destino</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($viajes as $viaje): ?> 
    <tr>
        <td><?php echo $viaje->Fecha; ?></td> <!-- Acceder correctamente a las propiedades del objeto -->
        <td><?php echo $viaje->Hora; ?></td>
        <td><?php echo $viaje->Origen; ?></td>
        <td><?php echo $viaje->Destino; ?></td>
        <td>
        <a href="<?= BASE_URL ?>editarViaje/<?= $viaje->ID_viaje ?>">Editar</a>
        <a href="<?= BASE_URL ?>eliminar/<?= $viaje->ID_viaje ?>">Eliminar</a>
        </td>
        <td>
            <a href="<?= BASE_URL ?>verMasViajes/<?= $viaje->ID_viaje ?>">Ver Más</a>
        </td>
    </tr>
<?php endforeach; ?>
        </tbody>
    </table>
</div>


<?php require_once 'templates/footer.phtml'; ?>