<?php require 'templates/header.phtml'; ?>

<div>
    <div>
        <h1>Viajes Disponibles</h1>
    </div>
</div>

<div>
    <div>
        <table>
            <thead>
                <tr>
                    <th>Temporada</th>
                    <th>Fecha salida</th>
                    <th>Horario</th>
                    <th>Origen</th>
                    <th>Destino</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($viajes as $viaje): ?>
                    <tr>
                        <td><?= $categoria->temporada ?></td>
                        <td><a href="<?= BASE_URL ?>verMasViajes/<?= $viaje->ID_viaje ?>" class=""><?= $viaje->Fecha ?> a <?= $viaje->Hora ?></a></td>
                        <td><?= $viaje->Origen ?></td>
                        <td>$ <?= $viaje->Destino ?></td>
                        <td>
                            <?php if (!empty($_SESSION['id'])): ?>
                                <div class="btn-group" role="group">
                                    <a href="<?= BASE_URL ?>eliminar/<?= $viaje->ID_viaje ?>" class="btn btn-outline-danger">Borrar</a>
                                    <a href="<?= BASE_URL ?>editarViaje/<?= $viaje->ID_viaje ?>" class="btn btn-outline-success">Editar</a>
                                </div>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require 'templates/footer.phtml'; ?>