<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<footer>
    <h2 class="titulofooter">Acerca de Aventure Time</h2>
    <p>Central de Pasajes es la plataforma de venta de pasajes de micro online líder en Argentina.
      Compr&aacute; tu pasaje de micro low cost de forma simple, rápida y segura. Aprovech&aacute; las ofertas comprando
      con anticipaci&oacute;n tu pasaje a Mar del Plata, Buenos Aires, Villa Gesel, Olavarria, Tandil y todos los
      destinos de Argentina. No pierdas tiempo yendo a la terminal, compr&aacute; online entre todas las empresas de
      colectivo: Flecha Bus, Via Tac, Via Bariloche, Condor y muchas más. ¡Viaj&aacute; en bus al mejor precio con
      Aventure Time!</p>
    </footer>
</body>
</html>