<?php require_once './templates/header.phtml' ?>

<?php if($error): ?>
    <div class="alert alert-danger" role="alert">
    <?= $error ?>
    </div>
<?php endif ?>

<form action="login" method="POST">
    <div class="form-group">
        <label for="gmail">Gmail</label>
        <input type="gmail" class="form-control" id="gmail" name="gmail" required>
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>

<?php require_once './templates/footer.phtml' ?>