<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/style.css">
    <title>Aventure time</title>
</head>
<body>
<header>
<?php if (isset($user) && $user): ?>
    <li class="nav"><a href="logout"><button>Cerrar Sesión</button></a></li>
<?php else: ?>
    <li class="nav"><a href="login"><button>Iniciar Sesión</button></a></li>
<?php endif; ?>



    </ul>
</header>