<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>css/style.css">
    <title>Aventure time</title>
</head>
<body>
<header>
    <ul class="barraNavegacion">
        <li class="nav">Aventura Time</li>
        <li class="nav"><a href="iniciarsesion"><button>Iniciar Sesion</button></a></li>
    </ul>
</header>