<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form action="agregar" method="POST">
        <div>
          <p class="titulo">Origen</p>
          <select class="selector" name="origen">
            <option value="Selecciona tu origen" disabled selected>Selecciona tu origen</option>
            <option value="Buenos Aires">Buenos Aires</option>
            <option value="Mar Del Plata">Mar Del Plata</option>
            <option value="Necochea">Necochea</option>
            <option value="Villa Gesel">Villa Gesel</option>
            <option value="Tandil">Tandil</option>
          </select>
          <p class="titulo">Destino</p>
          <select class="selector" name="destino">
            <option value="Selecciona tu destino" disabled selected>Selecciona tu destino</option>
            <option value="Buenos Aires">Buenos Aires</option>
            <option value="Mar Del Plata">Mar Del Plata</option>
            <option value="Necochea">Necochea</option>
            <option value="Villa Gesel">Villa Gesel</option>
            <option value="Tandil">Tandil</option>
          </select>
        </div>
        <div>
            <p class="titulo">Fechas</p>
            <input class="fecha" type="date" name="fecha" placeholder="Ida">
          </div>
       <div>
            <p>Hora</p>
        <input type="text" name="hora">
       </div>
</body>
</html>