<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="agregar" method="POST">
        <div>
            <input type="text" name="nombre">
            <input type="gmail" name="gmail">
            <input type="text" name="dni">
            <input type="password" name="password">
        </div>

    </form>
</body>
</html>